@startuml
title Crypto Exchange Interchain Blockchain (IBC) Protocol Flow of Funds Example
actor   Alice
Collections CosmosHub
Collections KavaChain
Collections CryptoExchange
entity Relayer #Green


Alice -> CosmosHub : Escrow 100 ATOMs on IBC Channel to KavaChain and generate IBC Packet
note left: 100 ATOMs in escrow on CosmosHub
Relayer -> KavaChain : Publish Packet on Kavachain
KavaChain -> Alice : Mint 100 KavaATOMs on KavaChain to Alice
note left: 100 KavaATOMs created on KavaChain
Alice -> KavaChain : Destroy 100 KavaATOMs on IBC Channel to CosmosHub and generate IBC Packet
note right: 100 KavaChain tokens destroyed
Relayer -> CosmosHub: Release 100 ATOMs from Escrow
CosmosHub -> Alice: Send ATOMs to Alice account on the Cosmos Hub
note left: Escrow of 100 ATOMs is released
Alice -> CryptoExchange : Trade 100 tokens in CryptoExchange Wallet
note right: CryptoExchange wallet sees 100 tokens from KavaChain(?)

@enduml