@startuml
title Crypto Exchange Interchain Blockchain (IBC) Protocol Flow of Funds Example
actor   Alice
Collections CosmosHub
Alice -> CosmosHub : Escrow 100 tokens on CosmosHub
Alice -> CosmosHub : Mint 100 tokens on KavaChain
note left: 100 tokens in escrow on CosmosHub
actor   Reyaler
Relayer -> KavaChain : Mint 100 tokens on KavaChain
KavaChain -> Relayer : Message received and tokens minted
note left: 100 tokens created on KavaChain

KavaChain -> Alice : 100 tokens created on KavaChain
Alice -> KavaChain : Destroy 100 Tokens on KavaChain
note right: 100 KavaChain tokens destroyed
note left: Escrow of 100 tokens is released

Collections KavaChain
Collections CryptoExchange
Alice -> CosmosHub : Send 100 tokens to CryptoExchange Wallet

Alice -> CryptoExchange : Trade 100 tokens in CryptoExchange Wallet
note right: CryptoExchange wallet sees 100 tokens from KavaChain(?)